version: 2.1
executors:
  frontend-executor:
    docker:
      - image: circleci/node:12.0

  workflows:
    all-check:
      jobs:
        - echo-name:
            filters:
              branches:
                only:
                  - develop

jobs:
  echo-name:
    executor: frontend-executor
    steps:
      - checkout
      - run: echo "Hello develop"
