version: 2.1
executors:
  frontend-executor:
    docker:
      - image: circleci/node:10.15.3

workflows:
  version: 2
  all-check:
    jobs:
      - echo:
          # filters:
          #   branches:
          #     only:
          #       - develop

jobs:
  echo:
    executor: frontend-executor
    steps:
      - checkout
      - run: echo "Hello develop"
